title: wndx2
description: web
url: https://github.com/Wndx2/Wndx2.github.io
author: wndx2
  name: James Park
  email: 22222w@duck.com
theme: wndxTheme
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitignore
  - .DS_Store